#!/usr/bin/env bash
# Integrate the Visualize AppImage with a per-user desktop environment.
#
# Installs hicolor icons plus a ~/.local/share/applications/visualize.desktop
# entry pointing at the AppImage, so GNOME Activities/dock (and other XDG
# environments) show the real application icon instead of a generic one.
# Idempotent, per-user, no root required.
#
# Usage:
#   scripts/integrate_appimage.sh [path/to/Visualize.AppImage | path/to/Visualize.AppDir] [--force] [--dry-run]
#
# Flags:
#   --force     overwrite an existing customize visualize.desktop that was
#               not generated by this script
#   --dry-run   print every action without touching $HOME
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MARKER="# Generated by scripts/integrate_appimage.sh (safe to overwrite)"

DRY_RUN=0
FORCE=0
TARGET=""
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    --force) FORCE=1 ;;
    -h|--help) sed -n '2,14p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) TARGET="$arg" ;;
  esac
done

die() { echo "Error: $*" >&2; exit 1; }

if [ -z "$TARGET" ]; then
  DEFAULT_TARGET="$SCRIPT_DIR/../dist_standalone/Visualize.AppImage"
  [ -e "$DEFAULT_TARGET" ] && TARGET="$DEFAULT_TARGET"
fi
[ -n "$TARGET" ] || die "pass the path of Visualize.AppImage (or its .AppDir)"
[ -e "$TARGET" ] && TARGET="$(readlink -f "$TARGET")"

msg() { printf '%s\n' "$*"; }
run() { # run <cmd...> : echo then execute unless --dry-run
  msg "  + $*"
  [ "$DRY_RUN" -eq 0 ] && "$@"
}

# Resolve the payload root: either an already-built AppDir or an extracted
# AppImage (--appimage-extract needs no FUSE). Extraction happens in a temp
# directory cleaned up on exit.
EXTRACT_WORK=""
cleanup() { [ -n "$EXTRACT_WORK" ] && rm -rf "$EXTRACT_WORK" || true; }
trap cleanup EXIT

case "$TARGET" in
  *.AppDir)
    [ -d "$TARGET" ] || die "directory not found: $TARGET"
    ROOT="$TARGET"
    LAUNCH_PATH="$TARGET/AppRun"
    [ "$DRY_RUN" -eq 0 ] && chmod u+x "$LAUNCH_PATH" 2>/dev/null || true
    ;;
  *)
    [ -f "$TARGET" ] || die "file not found: $TARGET"
    [ "$DRY_RUN" -eq 0 ] && chmod u+x "$TARGET" || true
    msg "Extracting $(basename "$TARGET") (temporary)..."
    EXTRACT_WORK="$(mktemp -d)"
    ( cd "$EXTRACT_WORK" && "$TARGET" --appimage-extract >/dev/null ) \
      || die "--appimage-extract failed; pass the Visualize.AppDir instead"
    ROOT="$EXTRACT_WORK/squashfs-root"
    LAUNCH_PATH="$TARGET"
    ;;
esac

[ -f "$ROOT/visualize.desktop" ] || die "visualize.desktop not found in $ROOT"

msg ""
msg "Integrating Visualize ($([ "$DRY_RUN" -eq 1 ] && echo dry-run)):"
ICON_BASE="$HOME/.local/share/icons/hicolor"

install_icon() { # install_icon <source> <dest>
  local src="$1" dst="$2"
  if [ -f "$src" ]; then
    run install -Dm644 "$src" "$dst"
    return 0
  fi
  return 1
}

for size in 48 64 128 256; do
  ICON_SRC="$ROOT/usr/share/icons/hicolor/$size/apps/visualize.png"
  # Root .DirIcon is a 256 px PNG per the AppImage spec.
  [ "$size" = "256" ] && [ ! -f "$ICON_SRC" ] && ICON_SRC="$ROOT/.DirIcon"
  if [ ! -f "$ICON_SRC" ]; then
    ASSET="$SCRIPT_DIR/../assets/icon-$size.png"
    [ "$size" = "256" ] && ASSET="$SCRIPT_DIR/../assets/icon.png"
    [ -f "$ASSET" ] && ICON_SRC="$ASSET"
  fi
  if install_icon "$ICON_SRC" "$ICON_BASE/$size/apps/visualize.png"; then
    :
  else
    msg "  ! no ${size}px icon found anywhere (skipped)"
  fi
done

SVG_SRC="$ROOT/usr/share/icons/hicolor/scalable/apps/visualize.svg"
[ -f "$SVG_SRC" ] || SVG_SRC="$SCRIPT_DIR/../assets/icon.svg"
install_icon "$SVG_SRC" "$ICON_BASE/scalable/apps/visualize.svg" \
  || msg "  ! no scalable icon found (skipped)"

# Launcher entry: rewrite Exec=<abs AppImage> %f, everything else kept
# verbatim (Name, Icon=visualize, StartupWMClass=Visualize, MimeType, ...).
DESKTOP_DST="$HOME/.local/share/applications/visualize.desktop"
if [ -f "$DESKTOP_DST" ] && ! grep -qF "$MARKER" "$DESKTOP_DST" && [ "$FORCE" -eq 0 ]; then
  msg "  ! keeping existing user-edited $DESKTOP_DST (use --force to replace)"
else
  DESKTOP_TMP="$(mktemp)"
  {
    echo "$MARKER"
    echo
    awk -v exec_line="Exec=\"$LAUNCH_PATH\" %f" '
      BEGIN { seen = 0 }
      /^Exec=/ { print exec_line; seen = 1; next }
      { print }
      END   { if (!seen) print exec_line }
    ' "$ROOT/visualize.desktop"
  } > "$DESKTOP_TMP"
  if [ "$DRY_RUN" -eq 1 ]; then
    msg "  + would install $DESKTOP_TMP -> $DESKTOP_DST"
    sed 's/^/      /' "$DESKTOP_TMP"
  else
    install -Dm644 "$DESKTOP_TMP" "$DESKTOP_DST"
    msg "  + installed $DESKTOP_DST"
  fi
  rm -f "$DESKTOP_TMP"
fi

if command -v gtk-update-icon-cache >/dev/null 2>&1; then
  run gtk-update-icon-cache -f -q "$ICON_BASE" || true
fi

msg ""
msg "OK. Launcher points to: $LAUNCH_PATH"
msg "Launch Visualize from Activities/GNOME search; pin it to the dock."
msg "If the dock still shows a generic icon, log out/in (or Alt+F2 r on X11)."